# .circleci/config.yml

version: 2.1

orbs:
  ruby: circleci/ruby@1.2.0
  macos: circleci/macos@2.1.0

jobs:
  build:
    macos:
      xcode: "13.1.0"
    working_directory: /Users/distiller/project
    shell: /bin/bash --login -o pipefail
    steps:
      - checkout
      - ruby/install-deps
      - run: gem install fastlane

workflows:
  basic: # This is the name of the workflow, feel free to change it to better match your workflow.
  # Inside the workflow, you define the jobs you want to run.
    jobs:
      - build

